---
title: "Scenario 1a.bio-10-gl-now"
output: 
  html_document:
      code_folding: hide
params:
  rep_csv: "p01_rep.csv"
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = T,
  message = F)
```

## 1a.bio-10%-gl-now

Obtain 10% for each biodiversity and habitat target in the high seas globally.

```{r}
library(prioritizr)
#devtools::load_all("~/github/prioritizr")
#library(bbnj)
devtools::load_all()
library(raster)
library(sf)
library(dplyr)
library(glue)
library(here)
library(formattable)
area = raster::area
select = dplyr::select

# prefix for scenario output
pfx        <- here("inst/scenarios/s01a.bio-10-gl-now")
rel_target <- 0.1
redo       <- F

# planning unit raster by area

#plot(p_abnj)
r_pu_area <- mask(area(r_pu_id), as_Spatial(p_abnj))
#plot(r_pu_area)

# biodiversity stack, excluding all and NA layers
#bio_tifs <- list.files(system.file("data/bio_gmbi", package="bbnj"), ".*\\.tif$", full.names=T)
#bio_s    <- stack(bio_tifs)
#bio_lyrs <- setdiff(names(bio_s), c("nspp_all", "nspp_na", "rls_all", "rls_na"))
#bio_s    <- subset(bio_s, bio_lyrs)
lyrs_bio <- setdiff(names(s_bio_gmbi), c("nspp_all", "nspp_na", "rls_all", "rls_na"))
s_bio    <- subset(s_bio_gmbi, lyrs_bio)

# feature stack
s_features <- stack(
  s_bio,
  #raster(s_fish_gfw, "mean_scaled_profits_with_subsidies") %>%
  #    gap_fill_raster() %>%
  #    rescale_raster(inverse=T),
  #raster(s_fish_ubc, "mcp_2004"),
  r_phys_seamounts,
  r_phys_vents,
  s_phys_scapes)
names(s_features) <- c(
  names(s_bio),
  #"gfw_profits.subsidized",
  #"saup_mcp.now",
  "seamounts_count",
  "vents_count",
  glue("benthscape_{1:11}"))

#plot(r_pu)

# setup problem
#options(error=utils::recover)
#options(error=NULL)

# mins <- raster::cellStats(raster::stack(as.list(s_features)), "min")
# mins[27]
# names(s_features)[27]

p <- problem(r_pu_area, s_features) %>%
  # Error: assert_that: missing values present in assertion
  add_min_set_objective() %>% 
  add_relative_targets(rel_target)
# Warning message:
# In verify_that(all(raster::cellStats(raster::stack(as.list(features)),  :
#   Elements 32 of raster::cellStats(raster::stack(as.list(features)), "min") >=  are not trueElements 32 of     0 are not true
```

```{r}
# solve
#devtools::load_all()
s <- solve_log(p, pfx, redo=redo)
```

```{r}
# plot 
read_csv(here("inst/scenarios/s01a.bio-10-gl-now_rep.csv")) %>% 
#attr(s, "feature_representation") %>% 
  mutate(
    relative_held = ifelse(is.nan(relative_held), 0, relative_held),
    relative_held = percent(relative_held),
    absolute_held = accounting(absolute_held)) %>% 
  formattable(list(
    relative_held = normalize_bar())) %>% 
  as.datatable(
    options = list(
      pageLength = 1000,
      columnDefs = list(list(className = 'dt-right', targets = c(2,3)))))
```


