---
title: "figures"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE)
```

```{r}
devtools::load_all()
library(tidyverse)
library(ggplot2)
```

```{r}

#Read in csv of report from scenario 4
targets <- readr::read_csv("inst/app/www/scenarios/s04a.biofish.alltime.mol50km_rep.csv") %>% 
## Add row for all seamounts together
  bind_rows(
    targets %>%
      filter(feature %in% c("phys_seamounts_gt200to800m", "phys_seamounts_gt800m", "phys_seamounts_0to200m")) %>%
      summarise_at("relative_held", mean) %>% 
      mutate(feature="phys_seamounts_all") 
  )

# targetsfig1<-dplyr::filter(targets, feature %in% c("phys_seamounts_all","phys_vents","bio_vgpm","scapes_hetero"))
# 
# targetsfig1labels <- c(phys_seamounts_all = "Seamounts", phys_vents = "Hydrothermal Vents", bio_vgpm = "Primary Productivity",scapes_hetero="Benthic Heterogeneity")
# 
# 
# ggplot(targetsfig1,aes(x=reorder(feature, relative_held),y=relative_held,label=scales::percent(relative_held)))+
#   geom_bar(stat="identity",width=0.5,fill="#4ba4b1")+
#   geom_hline(yintercept=0.3, linetype="dotted")+
#   coord_flip()+
#   scale_y_continuous(limits = c(0, 1),labels = scales::percent)+
#   scale_x_discrete(labels = targetsfig1labels)+
#   xlab("Conservation Feature")+
#   ylab("Percentage Included in Solution")+
#   geom_text(hjust = -0.4)
# 
# 
# targetsfig2<-dplyr::filter(targets, feature %in% c("nspp_corals","nspp_seagrasses","nspp_sharks.n.rays","nspp_cetaceans","X2100_nspp_corals","X2100_nspp_seagrasses","X2100_nspp_sharks.n.rays","X2100_nspp_cetaceans"))
# 
# targetsfig2labels <- c(nspp_corals = "Corals",nspp_cetaceans = "Cetaceans",nspp_sharks.n.rays = "Sharks and Rays", nspp_seagrasses = "Seagrasses",X2100_nspp_corals= "Corals 2100",X2100_nspp_cetaceans = "Cetaceans 2100",X2100_nspp_sharks.n.rays = "Sharks and Rays 2100",X2100_nspp_seagrasses = "Seagrasses 2100")
# 
# 
# ggplot(targetsfig2,aes(x=reorder(feature, relative_held),y=relative_held,label=scales::percent(relative_held)))+
#   geom_bar(stat="identity",width=0.5,fill="#4ba4b1")+
#   geom_hline(yintercept=0.3, linetype="dotted")+
#   coord_flip()+
#   scale_y_continuous(limits = c(0, 1),labels = scales::percent)+
#   scale_x_discrete(labels = targetsfig2labels)+
#   xlab("Conservation Feature")+
#   ylab("Percentage Included in Solution")+
#   geom_text(hjust = -0.4)
# 


targetsfig3<-dplyr::filter(targets, feature %in% c("phys_seamounts_all","phys_vents","bio_vgpm","scapes_hetero","nspp_seagrasses","nspp_corals","nspp_sharks.n.rays"))

targetsfig3labels <- c(phys_seamounts_all = "Seamounts", phys_vents = "Hydrothermal Vents", bio_vgpm = "Primary Productivity",scapes_hetero="Benthic Heterogeneity",nspp_seagrasses = "Seagrasses",nspp_corals="Corals", nspp_sharks.n.rays="Sharks and Rays")

base_size = 20

ggplot(targetsfig3,aes(x=reorder(feature, relative_held),y=relative_held,label=scales::percent(relative_held)))+
  geom_bar(stat="identity",width=0.5,fill="#4ba4b1")+
  geom_hline(yintercept=0.3, linetype="dotted", colour="white")+
  coord_flip()+
  scale_y_continuous(limits = c(0, 1),labels = scales::percent)+
  scale_x_discrete(labels = targetsfig3labels)+
  xlab("Conservation Feature")+
  ylab("Percentage Included in Solution")+
  geom_text(colour="white",hjust = -0.4, size=base_size*0.3)+
  theme(
      # Specify axis options
      axis.line = element_blank(),  
      axis.text.x = element_text(size = base_size*0.8, color = "white", lineheight = 0.9),  
      axis.text.y = element_text(size = base_size*0.8, color = "white", lineheight = 0.9),  
      axis.ticks = element_line(color = "white", size  =  0.2),  
      axis.title.x = element_text(size = base_size, color = "white", vjust=-2),  
      axis.title.y = element_text(size = base_size, color = "white"),  
      axis.ticks.length = unit(0.3, "lines"),
      # Specify panel options
      panel.background = element_rect(fill = "black", color  =  NA),  
      panel.border = element_rect(fill = NA, color = "white"),  
      panel.grid.major = element_blank(),  
      panel.grid.minor = element_blank(),  
      panel.spacing = unit(0.5, "lines"),   
      # Specify facetting options
      strip.background = element_rect(fill = "grey30", color = "grey10"),  
      strip.text.x = element_text(size = base_size*0.8, color = "white"),  
      strip.text.y = element_text(size = base_size*0.8, color = "white",angle = -90),  
      # Specify plot options
      plot.background = element_rect(color = "black", fill = "black"),  
      plot.title = element_text(size = base_size*1.2, color = "white"),  
      plot.margin = unit(rep(1, 4), "lines")
 
    )

ggsave("targetplot.png", width=16, height=9, units="in")

```

