---
title: "map layers"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```

```{r load layers}
library(prioritizr) # devtools::load_all("~/github/prioritizr")
#library(bbnj)       # 
devtools::load_all() # setwd(here()); devtools::install_local(force=T) 
# devtools::install_github("ecoquants/bbnj")
library(raster)
library(sf)
library(dplyr)
library(readr)
library(ggplot2)
library(stringr)
library(glue)
library(here)
library(fs)
library(units)
library(knitr)
library(formattable)
library(lwgeom)
library(RColorBrewer)
area   = raster::area
select = dplyr::select

# set rainbow color palette
pal  <- colorRampPalette(brewer.pal(11, "Spectral"))
cols <- rev(pal(255))

# variables ----
prjres     <- "_mol50km" # prjres in: View(projections_tbl)

P <- projections_tbl %>% filter(prjres == !!prjres)

# planning unit: ----
r_pu_id <- get_d_prjres("r_pu_id", prjres) # plot(r_pu_id)
r_pu <- setValues(r_pu_id, 1) %>% 
  mask(r_pu_id) # plot(r_pu)

# input layers ----
  eez<-get_d_prjres("p_eez_s05","_mol50km") %>% 
  rasterize(r_pu_id, field=1)


# biodiversity: now, for each taxonomic group ----
# s_bio_gmbi <- get_gmbi_grpsmdl_prjres("groups02", prjres)
#   lyrs_bio_now <- names(s_bio_gmbi) %>% 
#   setdiff(str_subset(names(s_bio_gmbi), "rli")) %>% 
#   setdiff(str_subset(names(s_bio_gmbi), "rls"))
# s_bio_now <- subset(s_bio_gmbi, lyrs_bio_now)

s_bio_now_all <- get_gmbi_grpsmdl_prjres("groups00", prjres) %>% 
  subset("groups00_nspp_all")

s_bio_future_all <- get_gmbi_grpsmdl_prjres("groups00_2100", prjres) %>% 
  subset("groups00_2100_nspp_all")

rls_all <- get_gmbi_grpsmdl_prjres("groups00", prjres) %>% 
  subset("groups00_rls_all")

# r_fish_effort_log <- get_d_prjres("s_fish_gfw", prjres)%>%
#   subset("fishing_KWH") %>% 
#   rescale_raster(log=T)

r_fish_effort <- get_d_prjres("s_fish_gfw", prjres)%>%
  subset("fishing_KWH")

# features ----
s_seamounts <- get_d_prjres("s_phys_seamounts",prjres)
lu_seamounts <- c(lteq200m="0to200",gt200lteq800m="gt200to800",gt800m="gt800")
lbls_seamounts <- sprintf("phys_seamounts_%sm", lu_seamounts[names(s_seamounts)])

seamounts_all <- sum(s_seamounts)

s_features <- stack(
  get_d_prjres("r_vgpm", prjres),
  s_bio_now_all,
  s_bio_future_all,
  rls_all,
  #raster(s_fish_gfw, "mean_scaled_profits_with_subsidies") %>%
  #    gap_fill_raster(r_mask=r_pu_id) %>%
  #    rescale_raster(inverse=T),
  #raster(s_fish_ubc, "mcp_2004"),
  s_seamounts,
  seamounts_all,
  get_d_prjres("r_phys_vents",prjres),
  get_d_prjres("r_phys_scapes_hetero",prjres))

names(s_features) <- c(
  "bio_vgpm",
  "s_bio_now_all",
  "s_bio_future_all",
  "rls_all",
  #"fish_profit.subs"
  #"fish_mcp.2004",
  lbls_seamounts,
  "seamounts_all",
  "phys_vents",
  "scapes_hetero")

```

```{r indiv layers}
dir_png <- here("inst/scripts/map_layers")
redo    <- F
  
summary30pct_csv <- glue("{dir_png}/_summary30pct.csv")

cell_km2 <- prod(res(r_pu)) %>% as_units("m2") %>% set_units("km2")
hs_ncells  <- length(na.omit(values(r_pu_id)))
hs_areakm2 <- hs_ncells * cell_km2

countries <- rnaturalearth::ne_countries(returnclass = "sf") %>%
  st_transform(P$epsg)
graticules <- st_graticule(countries)

# TODO
for (i in 1:nlayers(s_features)){ # i = 1
#for (i in 1:5){ # i = 1
  
  r   <- raster(s_features, i)
  lyr <- names(s_features)[i]
  
  r_tif      <- glue("{dir_png}/{lyr}.tif")
  map_png    <- glue("{dir_png}/{lyr}_map.png")
  map30_png  <- glue("{dir_png}/{lyr}_map30.png")
  hist30_png <- glue("{dir_png}/{lyr}_hist30.png")
  message(glue("{i}/{nlayers(s_features)}: {lyr}"))

  P   <- get_tif_projection(r_tif)
  
  # write raster ----
  if (!file.exists(r_tif)){
    message("  writeRaster")
    writeRaster(r, r_tif)
  }

  # values ----
  v <- values(r) %>% na.omit() %>% sort(decreasing = T)
  d <- tibble(v = v) %>% 
    filter(v > 0) %>% 
    mutate(
      v_cumsum    = cumsum(v),
      i           = 1:length(v),
      cumarea_km2 = i * cell_km2 %>% drop_units(),
      pct_totval  = v_cumsum/sum(v) * 100,
      pct_hsarea  = cumarea_km2/hs_areakm2 %>% drop_units() * 100)
  
  d_30 <- d %>% 
    filter(v_cumsum <= sum(v)*.3)
  
  v_at30     <- min(d_30$v)
  pcths_at30 <- max(d_30$pct_hsarea)
  title  <- glue("{lyr} — 30%: {round(pcths_at30, digits=2)}% hs >= {signif(v_at30)}")

  D_i <- tibble(
    lyr        = lyr,
    v_at30     = v_at30,
    pcths_at30 = pcths_at30)
  
  if (!file.exists(summary30pct_csv)){
    write_csv(D_i, summary30pct_csv)
  } else {
    read_csv(summary30pct_csv) %>% 
      filter(lyr != !!lyr) %>% 
      bind_rows(D_i) %>% 
      write_csv(summary30pct_csv)
  }
  
  # hist ----
  if (!file.exists(hist30_png) | redo){
    message("  hist30_png")
    #png(hist30_png, width=480*4, height = 480*4, res=300, units='px')
    p <- ggplot(d, aes(x=pct_hsarea, y=pct_totval)) + 
      geom_area(fill="gray70", color=NA) + 
      geom_area(data=d_30, aes(x=pct_hsarea, y=pct_totval), fill="gray10", color=NA) + 
      scale_fill_distiller("spectral") +
      theme_light() + 
      coord_cartesian(expand = F) +
      #scale_x_continuous(labels = scales::percent_format()) %>% 
      scale_x_continuous(labels = scales::percent_format(accuracy = 3)) %>% 
      scale_y_continuous(labels = scales::percent_format()) %>% 
      labs(
        title = title, 
        x="% high seas area", y="% total value")
    ggsave(
      hist30_png,
      p, 
      "png", width=6.4, height=6.4, dpi=300, units='in')
    #dev.off()
  }
  
  # map 30 ----
  if (!file.exists(map30_png)){
    message("  map30_png")
    png(map30_png, width=480*4, height = 480*4, res=300, units='px')
    
    #plot(r)
    r_v <- mask(r, r >= v_at30, maskvalue=0)
    plot(r, col = scales::alpha(cols, 0.3), legend=F, axes=F, box=F, main=title)
    plot(r_v, col = cols, add=T, legend=T)
    plot(st_geometry(countries), add=T, col=gray(0.8), border=gray(0.7), lwd=0.5)
    plot(st_geometry(graticules), add=T, col=gray(0.6), lwd=0.5)
    
    dev.off()
    map30_png %>%
      magick::image_read() %>% magick::image_trim() %>%
      magick::image_write(map30_png)
  }
  
  # map ----
  if (!file.exists(map_png)){
    message("  map_png")
    png(map_png, width=480*4, height = 480*4, res=300, units='px')
    
    #table(values(r))
    plot(r, col = cols, legend=T, axes=F, box=F, main=lyr)
    plot(st_geometry(countries), add=T, col=gray(0.8), border=gray(0.7), lwd=0.5)
    plot(st_geometry(graticules), add=T, col=gray(0.6), lwd=0.5)
    
    dev.off()
    map_png %>%
      magick::image_read() %>% magick::image_trim() %>%
      magick::image_write(map_png)
  }
}
```


```{r top 30% layers as simple sum map}
D <- read_csv(summary30pct_csv)

if (exists("s_b")) rm(s_b)
r_sol <- r_pu - 1 # plot(R_b)
for (i in 1:nlayers(s_features)){ # i = 3
  
  r <- s_features[[i]]
  lyr <- names(s_features)[i]
  
  v_at30 <- D %>% 
    filter(lyr == !!lyr) %>% 
    pull(v_at30)
  
  r_sol[r >= v_at30] <- 1
  
  sol_areakm2  <- sum(values(r_sol), na.rm = T) * cell_km2
  pct_sol_hs <-  sol_areakm2 / hs_areakm2 * 100 # 84.47849 % high seas
  title <- glue("{i}/{nlayers(s_features)}: +{lyr}, {round(pct_sol_hs, digits=2)}% hs")
  
  Sys.sleep(1)
  plot(r_sol, main = title)
}
sol30_tif <- glue("{dir_png}/sol30.tif")
sol30_map_png <- glue("{dir_png}/sol30_map.png")

writeRaster(r_sol, sol30_tif)

png(sol30_map_png, width=480*4, height = 480*4, res=300, units='px')
#table(values(r))
plot(r_sol, legend=F, axes=F, box=F)
plot(st_geometry(countries), add=T, col=gray(0.8), border=gray(0.7), lwd=0.5)
plot(st_geometry(graticules), add=T, col=gray(0.6), lwd=0.5)
dev.off()
sol30_map_png %>%
  magick::image_read() %>% magick::image_trim() %>%
  magick::image_write(sol30_map_png)
```

```{r fishing effort}

  r <- r_fish_effort
  lyr <- names(r_fish_effort)
  #plot(r)
  dir_png <- here("inst/scripts/map_layers")
  r_tif   <- glue("{dir_png}/{lyr}.tif")
  map_png <- glue("{dir_png}/{lyr}_map.png")
  
  writeRaster(r, r_tif, overwrite=T)
  
  P <- get_tif_projection(r_tif)
  
  pal <- colorRampPalette(brewer.pal(7, "YlOrRd"))
  cols <- (pal(7))
  
  # plot ----
  countries <- rnaturalearth::ne_countries(returnclass = "sf") %>%
    st_transform(P$epsg)
  graticules <- st_graticule(countries)
  
  png(map_png, width=480*4, height = 480*4, res=300, type="cairo", units='px', bg = "transparent")
  
  plot(r, breaks=c(0,10000,30000,100000,300000,1000000,5000000,108528675),col=cols, legend=F, axes=F, box=F)
  plot(eez, add=T, col=gray(0.9), legend=F)
  plot(st_geometry(countries), add=T, col=gray(0.8), border=gray(0.7), lwd=0.5)
  plot(st_geometry(graticules), add=T, col=gray(0.6), lwd=0.5)
  
  dev.off()
  map_png %>%
    magick::image_read() %>% magick::image_trim() %>%
    magick::image_write(map_png)

```


```{r solution & ebsas}
s04 <- raster(here("inst/app/www/scenarios/s04a.biofish.alltime.mol50km_sol.tif"))

ebsa_abnj<-read_sf(here("inst/scripts/data_overlays/ebsa_abnj.shp")) %>% 
  st_transform(54009)

map_png <- here("inst/scripts/map_overlays/s04ebsa.png")

countries <- rnaturalearth::ne_countries(returnclass = "sf") %>%
  st_transform(54009)
graticules <- st_graticule(countries)

png(map_png, width=480*4, height = 480*4, res=300, type="cairo", units='px', bg = "transparent")


plot(s04, alpha=0.8, legend=F, axes=F, box=F)
plot(st_geometry(ebsa_abnj), add=T, col=scales::alpha("blue", .3), border="transparent")
plot(st_geometry(countries), add=T, col=gray(0.8), border=gray(0.7), lwd=0.5)
plot(st_geometry(graticules), add=T, col=gray(0.6), lwd=0.5)

dev.off()

map_png %>%
  magick::image_read() %>% magick::image_trim() %>%
  magick::image_write(map_png)
```

```{r solution polygon ggridges layers}
library(tidyr)
library(scales)

extract <- raster::extract

sol_shp <- here("inst/app/www/scenarios/s04a.biofish.alltime.mol50km_sol_gcs.shp")

sol_sf <- read_sf(sol_shp)

ply <- sol_sf %>% arrange(desc(are_km2)) %>% head(1)
# mapview::mapview(ply)

ply_mol_sp <- ply %>% st_transform(P$epsg) %>% as("Spatial")

d_ply <- extract(s_features, ply_mol_sp, df=T) %>% 
  as_tibble() %>% 
  select(-ID) %>% 
  gather("layer", "value") %>% 
  na.omit() %>% 
  mutate(
    source = "ply")

d_hs <- values(s_features) %>% 
  as_tibble() %>% 
  gather("layer", "value") %>% 
  na.omit() %>% 
  mutate(
    source = "hs")

d_vs <- bind_rows(
  d_hs,
  d_ply) %>% 
  mutate(
    score = rescale(value))

d_vs_avg <- d_vs %>% 
  group_by(source, layer) %>% 
  summarize(
    avg_score = mean(score))

d_vs_avg_w <- d_vs_avg %>% 
  ungroup() %>% 
  mutate(source = glue("avg_{source}")) %>% 
  spread(source, avg_score) %>% 
  mutate(
    pct_ply = avg_ply / avg_hs) %>% 
  arrange(desc(pct_ply))

# TODO: include s04 features
d_vs_avg_w # YES!

DT::datatable(d_vs_avg_w)
ggplot(d_vs, aes(x = score, y = layer, fill = source)) +
  #geom_density_ridges_gradient(scale = 3, rel_min_height = 0.01) +
  geom_density_ridges(alpha = .5, color = "white") #+
  # geom_segment(
  #   aes(x = avg_pct, y = layer, xend = avg_pct, yend = layer + 1),
  #   data = d_vs_avg)

  #geom_vline(aes(xintercept = avg, y = layer), data = d_vs_avg) +
  #theme_ridges(font_size = 20, grid=TRUE, line_size=1, 
  #             center_axis_labels=TRUE)
  #scale_fill_viridis(name = "Temp. [F]", option = "C") #+
  #scale_fill_distiller("spectral", name = "value") #+
  #scale_fill_gradientn(colors = cols, name = "value") #+

png(hist_png, width=480*4, height = 480*4, res=300, units='px')
ggplot(d_features, aes(x = value, y = layer, fill = ..x..)) +
  #geom_density_ridges_gradient(scale = 3, rel_min_height = 0.01) +
  geom_density_ridges_gradient() +
  
  #scale_fill_viridis(name = "Temp. [F]", option = "C") #+
  #scale_fill_distiller("spectral", name = "value") #+
  scale_fill_gradientn(colors = cols, name = "value") #+
#labs(title = 'Temperatures in Lincoln NE in 2016')
dev.off()


library(ggridges)
library(forcats)
Catalan_elections %>%
  mutate(YearFct = fct_rev(as.factor(Year))) %>%
  ggplot(aes(y = YearFct)) +
  geom_density_ridges(
    aes(x = Percent, fill = paste(YearFct, Option)), 
    alpha = .8, color = "white", from = 0, to = 100
  ) +
  labs(
    x = "Vote (%)",
    y = "Election Year",
    title = "Indy vs Unionist vote in Catalan elections",
    subtitle = "Analysis unit: municipalities (n = 949)",
    caption = "Marc Belzunces (@marcbeldata) | Source: Idescat"
  ) +
  scale_y_discrete(expand = c(0.01, 0)) +
  scale_x_continuous(expand = c(0.01, 0)) +
  scale_fill_cyclical(
    breaks = c("1980 Indy", "1980 Unionist"),
    labels = c(`1980 Indy` = "Indy", `1980 Unionist` = "Unionist"),
    values = c("#ff0000", "#0000ff", "#ff8080", "#8080ff"),
    name = "Option", guide = "legend"
  ) +
  theme_ridges(grid = FALSE)

```

