---
title: "mapedit_solution"
author: "Morgan Visalli"
date: "8/24/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r cars}
library(mapview)
library(mapedit)
library(sf)
library(dplyr)
library(raster)
library(here)
mapviewOptions(basemaps = c("Esri.OceanBasemap","Stamen.TonerLite"))

shp <- here("inst/app/www/scenarios/s04a.biofish.alltime.mol50km_sol_gcs.shp")
tif <- here("inst/app/www/scenarios/s04a.biofish.alltime.mol50km_sol.tif")

#ply <- read_sf(shp)
r <- raster(tif) # plot(r)
pts <- rasterToPoints(r, spatial=T) %>% 
  st_as_sf() %>% 
  filter(s04a.biofish.alltime.mol50km_sol == 1)
plot(pts)

pts <- selectFeatures(pts, cex=0.5)
ply_edited <- editFeatures(ply)
mapvew()

library(mapedit)
library(mapview)

lf <- mapview()

# draw some polygons that we will select later
drawing <- lf %>%
  editMap()

# little easier now with sf
mapview(drawing$finished)

# especially easy with selectFeatures
selectFeatures(drawing$finished)
```
