---
output: 
  html_document:
      code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo=T, message=F)
```

```{r libraries & path}
library(prioritizr) # devtools::load_all("~/github/prioritizr")
#library(bbnj)       # 
devtools::load_all() # setwd(here()); devtools::install_local(force=T) 
# devtools::install_github("ecoquants/bbnj")
library(raster)
library(sf)
library(dplyr)
library(readr)
library(stringr)
library(glue)
library(here)
library(fs)
library(knitr)
library(formattable)
area   = raster::area
select = dplyr::select
```

MCP 2004 (jack mackerel removed)

```{r}

  r_pu_id <- get_d_prjres("r_pu_id", "_mol50km")

 r_fish_saup_2004<- get_d_prjres("s_fish_saup_v2","_mol50km")%>%
    subset("mcp_2004")

plot(r_fish_saup_2004)

```

<!-- MCP 2004 (jack mackerel removed) Gap Filled -->

<!-- ```{r} -->

<!--  r_fish_saup_2004_gap <- r_fish_saup_2004 %>% -->
<!--    gap_fill_raster() -->

<!--  plot(r_fish_saup_2004_gap) -->

<!-- ``` -->

<!-- MCP 2004 (jack mackerel removed) Rescaled -->

<!-- ```{r} -->
<!--  r_fish_saup_2004_rescale <- r_fish_saup_2004_gap %>% -->
<!--    rescale_raster() -->

<!--  plot(r_fish_saup_2004_rescale) -->
<!-- ``` -->

MCP 2004 (jack mackerel removed)  Rescaled + Log

```{r}
r_fish_saup_2004_log <- r_fish_saup_2004 %>%
  gap_fill_raster() %>% 
  rescale_raster(log=T)

plot(r_fish_saup_2004_log)
```

MCP 2050 (jack mackerel removed)

```{r}

  r_pu_id <- get_d_prjres("r_pu_id", "_mol50km")

 r_fish_saup_2050<- get_d_prjres("s_fish_saup_v2","_mol50km")%>%
    subset("mcp_2050")

plot(r_fish_saup_2050)

```

<!-- MCP 2050 (jack mackerel removed) Gap Filled -->

<!-- ```{r} -->

<!-- r_fish_saup_2050_gap <- r_fish_saup_2050 %>% -->
<!--   gap_fill_raster() -->

<!-- plot(r_fish_saup_2050_gap) -->

<!-- ``` -->

<!-- MCP 2050 (jack mackerel removed) Rescaled -->

<!-- ```{r} -->
<!-- r_fish_saup_2050_rescale <- r_fish_saup_2050_gap %>% -->
<!--   rescale_raster() -->

<!-- plot(r_fish_saup_2050_rescale) -->
<!-- ``` -->

MCP 2050 (jack mackerel removed)  Rescaled + Log

```{r}
r_fish_saup_2050_log <- r_fish_saup_2050 %>%
  gap_fill_raster() %>% 
  rescale_raster(log=T)

plot(r_fish_saup_2050_log)
```
