---
title: "prep_seamounts_Yesson-et-al-2011"
author: "Ben Best"
date: "12/7/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source(here::here("inst/scripts/setup.R"))

seamounts_kml <- file.path(dir_data_gdrive, "raw/Seamounts - Kim and Wessel 2011/KWSMTSv01.kml")
dir_seamounts_out <- file.path(dir_data_gdrive, "derived/seamounts")
r_tif <- file.path(dir_seamounts_out, "seamounts_count.tif")
```

```{r too slow, eval=F}
# elegant, but too slow -- takes 1 day
lyrs <- rgdal::ogrListLayers(seamounts_kml)
pt_lyr <- function(lyr){ # lyr=lyrs[[100]]
  n <- length(lyrs)
  i <- which(lyr==lyrs)
  t_now <- Sys.time()
  t_eta <- t_now + (t_now - t0)/i * (n - i)
  cat(glue("{i}/{n}: {lyr} -- ETA {t_eta}\n\n"))
  # 456/24643: KW-00456 -- ETA 2018-12-08 05:37:50
  # > Sys.time()
  # [1] "2018-12-07 14:38:00 PST"
  
  read_sf(seamounts_kml, layer=lyr)
}
t0 <- Sys.time()
pts <- map(lyrs, pt_lyr) %>% 
  reduce(rbind)

#devtools::install_github("briatte/tidykml")
#library(tidykml)
#pts <- tidykml::kml_points(seamounts_kml)
library(xml2)

#snip_xml <- file.path(dir_data_gdrive, "raw/Seamounts - Kim and Wessel 2011/KWSMTSv01 snip.xml")

```

```{r}
x <- read_xml(seamounts_kml)

xpaths <- list(
  name = "/d1:kml/d1:Document/d1:Folder/d1:Folder/d1:name",
  xyz  = "/d1:kml/d1:Document/d1:Folder/d1:Folder/d1:Placemark/d1:Point/d1:coordinates")
pts <- tibble(
  names = xml_find_all(x, xpaths$name) %>% xml_text(),
  xyz   = xml_find_all(x, xpaths$xyz) %>% xml_text()) %>% 
  separate(xyz, c("x", "y", "z"), sep=",", convert=T) %>% 
  st_as_sf(coords = c("x", "y"), crs = 4326)


r_na <- raster(
  xmn = -180, xmx = 180, ymn = -90, ymx = 90,
  resolution=0.5, crs=leaflet:::epsg4326)

r_cnt <- rasterize(st_coordinates(pts), r_na, fun='count', background=0)
writeRaster(r_cnt, r_tif)

plot(r_cnt)
```

