---
title: "prep benthic"
author: "Ben Best"
date: "12/7/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source(here::here("inst/scripts/setup.R"))

dir_raw <- file.path(dir_data_gdrive, "raw/Harris and Whiteway 2009")
dir_out <- file.path(dir_data_gdrive, "derived/benthic")
tif <- file.path(dir_data_gdrive, "derived/benthic/benthic_scapes11.tif")
```


```{r}
arc <- file.path(dir_raw, "Global_Seascapes/class_11")
r <- raster(arc)
r <- shift(r, y=90-extent(r)[4])
r
# class       : RasterLayer 
# dimensions  : 1800, 3600, 6480000  (nrow, ncol, ncell)
# resolution  : 0.1, 0.1  (x, y)
# extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
# coord. ref. : +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0 
# data source : /Users/bbest/Google Drive/projects/Pew BBNJ/data/raw/Harris and Whiteway 2009/Global_Seascapes/class_11 
# names       : class_11 
# values      : 1, 11  (min, max)
# attributes  :
#        ID  COUNT    CLASS_NAMES       RED GREEN BLUE OPACITY
#  from:  1 555279  1. unlabelled 0.0000000     1    0       1
#  to  : 11 154475 11. unlabelled 0.5019608     1    1       1
writeRaster(r, tif)
```

