---
title: "Sala y Gomez"
output:
  html_document:
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

```{r}
devtools::load_all()
library(raster)
library(sf)
library(tidyverse)
library(glue)
library(here)
library(fs)
library(knitr)
library(formattable)
library(mapview)
library(DT)
area   = raster::area
select = dplyr::select
```

```{r}
salaygomez<-read_sf(here("inst/scripts/salaygomez/s04a_salaygomez_mol50km.shp")) %>% 
  select("rmpshpr")

salaygomezebsa<-read_sf(here("inst/scripts/salaygomez/salaygomezebsa.shp"))

s04<-read_sf(here("inst/app/www/scenarios/s04a.biofish.alltime.mol50km_sol_gcs.shp"))

mapview(s04, col.regions="yellow")+mapview(salaygomezebsa, col.regions="blue")+mapview(salaygomez, col.regions="green")

```



```{r sala y gomez stats}

prjres     <- "_mol50km"


salaygomezstats<-tribble(
  ~feature, ~amountsg)

#Hydrothermal Vents
vents_sg<-mask(get_d_prjres("r_phys_vents",prjres), salaygomez)
salaygomezstats<-tibble::add_row(salaygomezstats, feature="vents", amountsg=cellStats(vents_sg, stat="sum",na.rm=TRUE))

#Seamounts
seamounts_all <- sum(get_d_prjres("s_phys_seamounts",prjres))

seamounts_sg<-mask(seamounts_all, salaygomez)
salaygomezstats<-tibble::add_row(salaygomezstats, feature="seamounts", amountsg=cellStats(seamounts_sg, stat="sum",na.rm=TRUE))

#Species Richness
s_bio_gmbi <- get_gmbi_grpsmdl_prjres("groups02", prjres)
  lyrs_bio_now <- names(s_bio_gmbi) %>%
  setdiff(str_subset(names(s_bio_gmbi), "rli")) %>%
  setdiff(str_subset(names(s_bio_gmbi), "rls"))
s_bio_now <- subset(s_bio_gmbi, lyrs_bio_now)

nspp_sg<-mask(s_bio_now, salaygomez)
salaygomezstats<-tibble::add_row(salaygomezstats, feature=lyrs_bio_now, amountsg=cellStats(nspp_sg, stat="max",na.rm=TRUE))

#Benthic Heterogeneity
# scapes_sg<-mask(get_d_prjres("r_phys_scapes_hetero",prjres), salaygomez)
# salaygomezstats<-tibble::add_row(salaygomezstats, feature="seascapes", amountsg=cellStats(scapes_sg, stat="max",na.rm=TRUE))

all_scapes <- get_d_prjres("s_phys_scapes", prjres)
lyrs_scapes <- names(all_scapes)

all_scapes_sg<-mask(all_scapes, salaygomez)
salaygomezstats<-tibble::add_row(salaygomezstats, feature=lyrs_scapes, amountsg=cellStats(all_scapes_sg, stat="max",na.rm=TRUE))

datatable(salaygomezstats)

```

```{r salaygomez map inset}

  map_png <- here("inst/scripts/salaygomez/sgmapinset.png")
  map_png_zoom <-here("inst/scripts/salaygomez/sgmapinsetzoom.png")

  countries <- rnaturalearth::ne_countries(returnclass = "sf") %>%
    st_transform(54009)
  graticules <- st_graticule(countries)
  
  png(map_png, width=480*4, height = 480*4, res=300, type="cairo", units='px', bg = "transparent")
  
  
  plot(r, alpha=0.5, legend=F, axes=F, box=F)
  plot(st_geometry(salaygomez), add=T, col="#00a600", border="transparent")
  plot(st_geometry(countries), add=T, col=gray(0.8), border=gray(0.7), lwd=0.5)
  plot(st_geometry(graticules), add=T, col=gray(0.6), lwd=0.5)
  
  dev.off()
  
  map_png %>%
    magick::image_read() %>% magick::image_trim() %>%
    magick::image_write(map_png)
  
  
  ##Zoomed image
  
  png(map_png_zoom, width=480*4, height = 480*4, res=300, type="cairo", units='px')
  
  plot(r)
  e <-drawExtent()
  
  plot(r, alpha=0.5, legend=F, axes=F, box=F, ext=extent(e))
  plot(st_geometry(salaygomez), add=T, col="#00a600", border="transparent")
  plot(st_geometry(countries), add=T, col=gray(0.8), border=gray(0.7), lwd=0.5)

  
  dev.off()
  
  map_png_zoom %>%
    magick::image_read() %>% magick::image_trim() %>%
    magick::image_write(map_png_zoom)


```

