---
title: "test mollweide"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```

```{r}
library(dplyr)
library(leaflet)
library(bbnj)
library(glue)
library(raster)

map <- leaflet(
  options =
    leafletOptions(
      crs=leafletCRS(crsClass="L.Proj.CRS", code=glue('EPSG:{projections_lst$mol$epsg}'),
                     proj4def= projections_lst$mol$proj,
                     resolutions = c(65536, 32768, 16384, 8192, 4096, 2048)))) %>%
  addGraticule(style= list(color= '#999', weight= 0.5, opacity= 1)) %>%
  addGraticule(sphere = TRUE, style= list(color= '#777', weight= 1, opacity= 0.25)) %>%
  addPolygons(
    data=p_countries, group = 'land', weight = 1, color = '#4D4D4D') # gplots::col2hex('gray30'): '#4D4D4D'
map

tif <- "/Users/bbest/github/bbnj/inst/app/www/scenarios/s00a.bio.30pct.gl.mer_sol.tif"
r <- raster(tif)
#plot(r)
# DOH! https://rstudio.github.io/leaflet/projections.html
# addRasterImage currently works only with EPSG:3857 Web Mercator

library(ggplot2)
library(rasterVis)
library(plotly)
library(ggthemes)
library(stringr)
library(sf)
library(leafem)

p_countries_mol <- get_o_prjres("p_countries", "_mol")
cols <- c("0" = "blue", "1" = "green")

g <- gplot(r) + 
  geom_tile(aes(fill = factor(value))) + 
  scale_fill_manual(values = cols) +
  theme_map() + 
  coord_equal() #+
  #geom_sf(data = p_countries_mol, inherit.aes = F)
g

g <- ggplot() + 
  geom_sf(data = p_countries_mol, inherit.aes = F)


ggplotly(g)




ggplot() +
  geom_sf(data = p_countries)


#p_countries_mol <- st_buffer(p_countries_mol, 0)
p_countries_mol <- lwgeom::st_make_valid(p_countries_mol)
map <- tm_shape(p_countries_mol) + tm_polygons() #tm_polygons is the equivalent to tm_fill+tm_borders

tmap_mode("plot")
tm_shape(r) + tm_raster(
  col = "s00a.bio.30pct.gl.mer_sol", 
  palette = "Spectral",
  alpha = 0.8) +
  tm_shape(p_countries) + tm_polygons()
ggplotly(g)
map + # note that you can store maps as objects
  

tm_shape(r) + tm_raster(col = "s00a.bio.30pct.gl.mer_sol") #alpha = 0.7)


library(tmap)


tm_raster(r) + tm_fill()
  
g +  
  geom_sf(data=p_countries_mol)

, color = "gray", fill = "darkgray")
 
plotly::ggplotly(g)

gplot(r) +  
  geom_tile(data=r, aes(fill=factor(value),alpha=0.8))

ggplot() + 
  geom_raster(data = r) +
  geom_sf(data = cities, aes(size = pop), color = "red", alpha = 0.3)
ggplotly(p)


nc <- sf::st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE)
ggplot(nc) +
  geom_sf(aes(fill = AREA))

map %>% 
  addRasterImage(r, project = F) %>%
    r, colors = pal, opacity = opacity, project = F,
    layerId="lyr", group="Layer") %>%
      clearControls() %>%
      addLegend(
        group = "Layer", pal = pal,
        position = "bottomright",
        values = rng,
        title = input$sel_lyr %>%
          str_replace(fixed("."), ", ") %>%
          str_replace("_", "<br>")) %>%
      add_map_lyrsctl()
```

```{r mapdeck}
library(mapdeck)
key <- readLines("~/.mapbox_token")
set_token(key)
mapdeck_tokens()

tif <- "/Users/bbest/github/bbnj/inst/app/www/scenarios/s00a.bio.30pct.gl.mer_sol.tif"
r <- raster(tif)
p_sol <- raster::rasterToPolygons(r, dissolve=T) %>% 
  st_as_sf() %>% 
  st_transform(4326) %>%
  rename(v = s00a.bio.30pct.gl.mer_sol) %>%
  filter(!is.na(v), v > 0) %>%
  st_union() %>%
  st_collection_extract("POLYGON")


#p_r_2 <- p_r
p_r <- lwgeom::st_make_valid(p_r)
plot(p_r["s00a.bio.30pct.gl.mer_sol"])
#mapdeck(style = mapdeck_style("dark")) %>% 
#mapdeck(style ="mapbox://styles/mapbox/north-star") %>% 
# https://blog.mapbox.com/designing-north-star-c8574e299c94 
mapdeck(style ="mapbox://styles/bdbest/cjy45dso53b7i1cpfbpm99ody") %>% 
  add_polygon(
    p_r, 
    fill_colour = "s00a.bio.30pct.gl.mer_sol",
    fill_opacity = .7*255)

url <- 'https://raw.githubusercontent.com/plotly/datasets/master/2011_february_aa_flight_paths.csv'
flights <- read.csv(url)
flights$id <- seq_len(nrow(flights))
flights$stroke <- sample(1:3, size = nrow(flights), replace = T)

mapdeck( token = key, style = 'mapbox://styles/mapbox/dark-v9', pitch = 45 ) %>%
  add_arc(
    data = flights
    , layer_id = "arc_layer"
    , origin = c("start_lon", "start_lat")
    , destination = c("end_lon", "end_lat")
    , stroke_from = "airport1"
    , stroke_to = "airport2"
    , stroke_width = "stroke"
  )

```

