---
output: 
  html_document:
      code_folding: hide
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo=T, message=F)
```

```{r libraries & path}
library(prioritizr) # devtools::load_all("~/github/prioritizr")
library(bbnj)       # devtools::load_all() # devtools::install_local(force=T)
library(raster)
library(sf)
library(dplyr)
library(stringr)
library(glue)
library(here)
library(fs)
library(knitr)
library(formattable)
area   = raster::area
select = dplyr::select

rmd <- knitr::current_input(dir = T)
#rmd <- file.path(getwd(), "s01a.bio.10pct.gl.now.Rmd")
pfx <- rmd %>% path_ext_remove()
```

# `r basename(pfx)`

Obtain 30% for each biodiversity and habitat target in the high seas globally.

```{r solutions}
# variables: target 30% ----
rel_target <- 0.3
redo       <- T

# planning unit: cost by area ----
r_pu <- area(r_pu_id) %>% 
  mask(r_pu_id) # plot(r_pu)

# biodiversity: now, not 2100 ----
lyrs_bio_now <- names(s_bio_gmbi) %>% 
  setdiff(str_subset(names(s_bio_gmbi), "2100$")) %>% 
  # use taxonomic groups, so exclude all and NA layers
  setdiff(c("nspp_all", "nspp_na", "rls_all", "rls_na"))
s_bio_now <- subset(s_bio_gmbi, lyrs_bio_now)

# features ----
s_features <- stack(
  r_vgpm,
  s_bio_now,
  #raster(s_fish_gfw, "mean_scaled_profits_with_subsidies") %>%
  #    gap_fill_raster() %>%
  #    rescale_raster(inverse=T),
  #raster(s_fish_ubc, "mcp_2004"),
  s_phys_seamounts,
  r_phys_vents,
  s_phys_scapes)
names(s_features) <- c(
  "bio_vgpm",
  names(s_bio_now),
  #"fish_profit.subs"
  #"fish_mcp.2004",
  sprintf("phys_seamounts_%sm", c("0to200","gt200to800","gt800")),
  "phys_vents",
  glue("phys_scape.{1:11}"))

# problem ----
p <- problem(r_pu, s_features) %>%
  add_min_set_objective() %>% 
  add_relative_targets(rel_target)

# solve ----
s <- solve_log(p, pfx, redo=redo)

# plot 
tbl_target_representation(glue("{pfx}_rep.csv"))
```


