---
output: 
  html_document:
      code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo=T, message=F)
library(prioritizr) # devtools::load_all("~/github/prioritizr")
#library(bbnj)       # 
devtools::load_all() # setwd(here()); devtools::install_local(force=T) 
# devtools::install_github("ecoquants/bbnj")
library(raster)
library(sf)
library(dplyr)
library(readr)
library(stringr)
library(glue)
library(here)
library(fs)
library(knitr)
library(formattable)
area   = raster::area
select = dplyr::select

#message("library done")

if (interactive()){
  wd <- file.path(here::here(), "inst/app/www/scenarios/")
  setwd(wd) # getwd()
  if (!exists("rmd")){
    #rmd <- file.path(getwd(), "s00a.bio.30pct.gl.mol50km.Rmd")
    rmd <- file.choose()
  }
} else {
  rmd <- knitr::current_input(dir = T)  
}

pfx <- rmd %>% path_ext_remove()
tif <- glue("{pfx}_sol.tif")
```

```{r solution}
# variables ----
rel_target <- 0.3
prjres     <- "_mol50km" # prjres in: View(projections_tbl)
redo       <- T

# problem & solution ----
P <- projections_tbl %>% filter(prjres == !!prjres)
if (!file.exists(tif) | redo){
  
  # planning unit: ----
  r_pu_id <- get_d_prjres("r_pu_id", prjres) # plot(r_pu_id)
  r_pu <- setValues(r_pu_id, 1) %>% 
    mask(r_pu_id) # plot(r_pu)
  
  # biodiversity: now, not 2100 ----
  # devtools::load_all()
  s_bio_gmbi <- get_d_prjres("s_bio_gmbi", prjres)
  lyrs_bio_now <- names(s_bio_gmbi) %>% 
    setdiff(str_subset(names(s_bio_gmbi), "2100$")) %>% 
    setdiff(c("nspp_all", "nspp_na", "rls_all", "rls_na"))
  s_bio_now <- subset(s_bio_gmbi, lyrs_bio_now)
  
  # features ----
  s_features <- stack(
    get_d_prjres("r_vgpm", prjres),
    s_bio_now,
    #raster(s_fish_gfw, "mean_scaled_profits_with_subsidies") %>%
    #    gap_fill_raster() %>%
    #    rescale_raster(inverse=T),
    #raster(s_fish_ubc, "mcp_2004"),
    get_d_prjres("s_phys_seamounts",prjres),
    get_d_prjres("r_phys_vents",prjres),
    get_d_prjres("s_phys_scapes",prjres) %>%
      raster::subset(c("class_1","class_2","class_3","class_4","class_6","class_7","class_8","class_9","class_10","class_11")))
  names(s_features) <- c(
    "bio_vgpm",
    names(s_bio_now),
    #"fish_profit.subs"
    #"fish_mcp.2004",
    sprintf("phys_seamounts_%sm", c("0to200","gt200to800","gt800")),
    "phys_vents",
    glue("phys_scape.{c(1,2,3,4,6,7,8,9,10,11)}"))
  
  # problem ----
  p <- problem(r_pu, s_features) %>%
    add_min_set_objective() %>% 
    add_relative_targets(rel_target)
  
  # solve ----
  tif <- solve_log(p, pfx, redo=redo)
}
```

# `r basename(pfx)`

Obtain `r rel_target*100`% for each biodiversity and habitat target in the high seas globally, using projection `r P$name` (`r P$res` resolution).

Only seascapes with >50% of area in high seas included.

Included seascapes 1, 2, 5, 8, 9. This corresponds to seascapes 11, 10, 9, 3, 2 in Harris & Whiteway 2009.

```{r report}

# variables ----
redo       <- T

report_solution(tif)
```
